In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

In [2]:
import warnings
warnings.filterwarnings("ignore")

Prepare rules for the all the data sets 
1) Try different values of support and confidence. Observe the change in number of rules for different support,confidence      values
2) Change the minimum length in apriori algorithm
3) Visulize the obtained rules using different plots

In [3]:
books=pd.read_csv(r"C:\Users\ADITYA\Desktop\EXCELR ASSIGNMENT\ASSOCIATION RULE\book.csv")

In [4]:
books.head()

,ChildBks,YouthBks,CookBks,DoItYBks,RefBks,ArtBks,GeogBks,ItalCook,ItalAtlas,ItalArt,Florence
0,0,1,0,1,0,0,1,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0
3,1,1,1,0,1,0,1,0,0,0,0
4,0,0,1,0,0,0,1,0,0,0,0

In [5]:
books.shape

(2000, 11)

In [6]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ChildBks   2000 non-null   int64
 1   YouthBks   2000 non-null   int64
 2   CookBks    2000 non-null   int64
 3   DoItYBks   2000 non-null   int64
 4   RefBks     2000 non-null   int64
 5   ArtBks     2000 non-null   int64
 6   GeogBks    2000 non-null   int64
 7   ItalCook   2000 non-null   int64
 8   ItalAtlas  2000 non-null   int64
 9   ItalArt    2000 non-null   int64
 10  Florence   2000 non-null   int64
dtypes: int64(11)
memory usage: 172.0 KB

In [7]:
!pip install mlxtend

Requirement already satisfied: mlxtend in c:\users\aditya\anaconda3\lib\site-packages (0.20.0)
Requirement already satisfied: scipy>=1.2.1 in c:\users\aditya\anaconda3\lib\site-packages (from mlxtend) (1.7.3)
Requirement already satisfied: pandas>=0.24.2 in c:\users\aditya\anaconda3\lib\site-packages (from mlxtend) (1.4.3)
Requirement already satisfied: numpy>=1.16.2 in c:\users\aditya\anaconda3\lib\site-packages (from mlxtend) (1.21.5)
Requirement already satisfied: setuptools in c:\users\aditya\anaconda3\lib\site-packages (from mlxtend) (61.2.0)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\aditya\anaconda3\lib\site-packages (from mlxtend) (3.5.1)
Requirement already satisfied: joblib>=0.13.2 in c:\users\aditya\anaconda3\lib\site-packages (from mlxtend) (1.1.0)
Requirement already satisfied: scikit-learn>=1.0.2 in c:\users\aditya\anaconda3\lib\site-packages (from mlxtend) (1.0.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\aditya\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Requirement already satisfied: pillow>=6.2.0 in c:\users\aditya\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (9.2.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\aditya\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.25.0)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\aditya\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.0.4)
Requirement already satisfied: packaging>=20.0 in c:\users\aditya\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (21.3)
Requirement already satisfied: cycler>=0.10 in c:\users\aditya\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\aditya\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\aditya\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2022.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\aditya\anaconda3\lib\site-packages (from scikit-learn>=1.0.2->mlxtend) (2.2.0)
Requirement already satisfied: six>=1.5 in c:\users\aditya\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)

In [8]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
from mlxtend.preprocessing import TransactionEncoder

In [9]:
frequent_itemsets = apriori(books, min_support=0.1, use_colnames=True)
frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))
frequent_itemsets

C:\Users\ADITYA\anaconda3\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:111: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

    support                       itemsets  length
0    0.4230                     (ChildBks)       1
1    0.2475                     (YouthBks)       1
2    0.4310                      (CookBks)       1
3    0.2820                     (DoItYBks)       1
4    0.2145                       (RefBks)       1
5    0.2410                       (ArtBks)       1
6    0.2760                      (GeogBks)       1
7    0.1135                     (ItalCook)       1
8    0.1085                     (Florence)       1
9    0.1650           (ChildBks, YouthBks)       2
10   0.2560            (CookBks, ChildBks)       2
11   0.1840           (DoItYBks, ChildBks)       2
12   0.1515             (ChildBks, RefBks)       2
13   0.1625             (ChildBks, ArtBks)       2
14   0.1950            (ChildBks, GeogBks)       2
15   0.1620            (CookBks, YouthBks)       2
16   0.1155           (DoItYBks, YouthBks)       2
17   0.1010             (ArtBks, YouthBks)       2
18   0.1205            (GeogBks, YouthBks)       2
19   0.1875            (CookBks, DoItYBks)       2
20   0.1525              (CookBks, RefBks)       2
21   0.1670              (CookBks, ArtBks)       2
22   0.1925             (CookBks, GeogBks)       2
23   0.1135            (CookBks, ItalCook)       2
24   0.1055             (DoItYBks, RefBks)       2
25   0.1235             (DoItYBks, ArtBks)       2
26   0.1325            (DoItYBks, GeogBks)       2
27   0.1105              (GeogBks, RefBks)       2
28   0.1275              (GeogBks, ArtBks)       2
29   0.1290  (CookBks, ChildBks, YouthBks)       3
30   0.1460  (CookBks, DoItYBks, ChildBks)       3
31   0.1225    (CookBks, ChildBks, RefBks)       3
32   0.1265    (CookBks, ChildBks, ArtBks)       3
33   0.1495   (CookBks, ChildBks, GeogBks)       3
34   0.1045  (DoItYBks, ChildBks, GeogBks)       3
35   0.1020    (GeogBks, ChildBks, ArtBks)       3
36   0.1015    (CookBks, DoItYBks, ArtBks)       3
37   0.1085   (CookBks, DoItYBks, GeogBks)       3
38   0.1035     (CookBks, ArtBks, GeogBks)       3

In [21]:
frequent_itemsets[ (frequent_itemsets['length'] == 1) &
                   (frequent_itemsets['support'] >= 0.2) ]

   support    itemsets  length
0   0.4230  (ChildBks)       1
1   0.2475  (YouthBks)       1
2   0.4310   (CookBks)       1
3   0.2820  (DoItYBks)       1
4   0.2145    (RefBks)       1
5   0.2410    (ArtBks)       1
6   0.2760   (GeogBks)       1

In [23]:
frequent_itemsets[ (frequent_itemsets['length'] == 3) &
                   (frequent_itemsets['support'] >= 0.1) ]

    support                       itemsets  length
29   0.1290  (CookBks, ChildBks, YouthBks)       3
30   0.1460  (CookBks, DoItYBks, ChildBks)       3
31   0.1225    (CookBks, ChildBks, RefBks)       3
32   0.1265    (CookBks, ChildBks, ArtBks)       3
33   0.1495   (CookBks, ChildBks, GeogBks)       3
34   0.1045  (DoItYBks, ChildBks, GeogBks)       3
35   0.1020    (GeogBks, ChildBks, ArtBks)       3
36   0.1015    (CookBks, DoItYBks, ArtBks)       3
37   0.1085   (CookBks, DoItYBks, GeogBks)       3
38   0.1035     (CookBks, ArtBks, GeogBks)       3

In [22]:
rules = association_rules(frequent_itemsets,  min_threshold=0.7)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(RefBks),(ChildBks),0.2145,0.423,0.1515,0.706294,1.669725,0.060767,1.964548
1,(GeogBks),(ChildBks),0.2760,0.423,0.1950,0.706522,1.670264,0.078252,1.966074
2,(RefBks),(CookBks),0.2145,0.431,0.1525,0.710956,1.649549,0.060050,1.968556
3,(ItalCook),(CookBks),0.1135,0.431,0.1135,1.000000,2.320186,0.064582,inf
4,"(CookBks, YouthBks)",(ChildBks),0.1620,0.423,0.1290,0.796296,1.882497,0.060474,2.832545

In [19]:
rules = association_rules(frequent_itemsets,  min_threshold=1)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(ItalCook),(CookBks),0.1135,0.431,0.1135,1.0,2.320186,0.064582,inf

for 20% support and 60% confidence

In [32]:
frequent_itemsets2 = apriori(books, min_support=0.2, use_colnames=True)
frequent_itemsets2['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))
frequent_itemsets2

C:\Users\ADITYA\anaconda3\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:111: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

   support             itemsets  length
0   0.4230           (ChildBks)       1
1   0.2475           (YouthBks)       1
2   0.4310            (CookBks)       1
3   0.2820           (DoItYBks)       1
4   0.2145             (RefBks)       1
5   0.2410             (ArtBks)       1
6   0.2760            (GeogBks)       1
7   0.2560  (CookBks, ChildBks)       1

In [34]:
rules2 = association_rules(frequent_itemsets,  min_threshold=0.6)
rules2.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(YouthBks),(ChildBks),0.2475,0.423,0.1650,0.666667,1.576044,0.060308,1.731000
1,(ChildBks),(CookBks),0.4230,0.431,0.2560,0.605201,1.404179,0.073687,1.441240
2,(DoItYBks),(ChildBks),0.2820,0.423,0.1840,0.652482,1.542511,0.064714,1.660347
3,(RefBks),(ChildBks),0.2145,0.423,0.1515,0.706294,1.669725,0.060767,1.964548
4,(ArtBks),(ChildBks),0.2410,0.423,0.1625,0.674274,1.594028,0.060557,1.771427